### ISSUE TITLE
Place After Hours Order Feature

### ISSUE THREAD

**Issue by kuhner** [robinhood-unofficial/pyrh#195]
I don't think there is anything currently in this repo for submitting after hours orders. This would be a nice feature for people with Robinhood Gold. 
Anybody have an idea how to do this? 
I think it would just be adding a parameter to the request but I don't know what the param name is.

**Comment by kuhner** [comment]
Just tested this out. The order has been queued and when the order status is retrieved the 'extended_hours' value is true.
Code added:
payload['extended_hours'] = True
to line 1357 of Robinhood.py

More should be done to parameterize this in other functions but this should tell us if its do-able.

**Comment by adithyabsk** [comment]
@kuhner great, thanks for the input. I'll be looking at the core stock data procurement next
