### ISSUE TITLE
I'm having an issue even getting started.

### ISSUE THREAD

**Issue by DangerSquirrel-X** [robinhood-unofficial/pyrh#218]
# Description

I'm trying to follow the tutorial for the master branch, but I'm getting this error that says: "__init__() takes 1 positional argument but 3 were given" Again, I'm following the tutorial, does this mean the tutorial is out of date? If so, what do I do? This is all have right now:

`import logincred
from pyrh import Robinhood

robin = Robinhood(username=logincred.USERNAME,password=logincred.PASSWORD)
robin.login()

stonk = "SPHD"

robin.print_quote(stonk)
`
What am I missing?

**Comment by adithyabsk** [comment]
@DangerSquirrel-X not sure, can you please print the traceback along with the other information requested in the bug issue template (ie system info, project version, etc...)

**Comment by Zucce05** [comment]
I just started using this.
The quickstart guide is wrong.
Move the username and password creds to the login function call.
robin = Robinhood()
robin.login(username=logincred.USERNAME,password=logincred.PASSWORD)

**Comment by adithyabsk** [comment]
@DangerSquirrel-X @Zucce05 you're right! the latest release and master are not in sync as this project is undergoing heavy updates. Please use @Zucce05's advice to log in

**Comment by adithyabsk** [comment]
I've updated the README, but will update again once master is pushed to pypi
