### ISSUE TITLE
We should not include certs.pem in this repo

### ISSUE THREAD

**Issue by pengchaoandy** [robinhood-unofficial/pyrh#222]
#### Checklist
- [x] I am on the [latest](https://github.com/robinhood-unofficial/pyrh/releases/latest) pyrh version.
- [x] I have searched the [issues](https://github.com/robinhood-unofficial/pyrh/issues) of this repo and believe that this is not a duplicate.

# Description

We should use python-certifi, otherwise if someone doesn't update this package, they may use the old certi, which will induce safety issue.

**Comment by adithyabsk** [comment]
Fixed in fb1ed63501378ecf667d7637d0bd2122acb8c9ef
