### ISSUE TITLE
TypeError unsupported operand types for URL and str

### ISSUE THREAD

**Issue by samueleishion** [robinhood-unofficial/pyrh#229]
#### Checklist
- [X] I am on the [latest](https://github.com/robinhood-unofficial/pyrh/releases/latest) pyrh version.
- [X] I have searched the [issues](https://github.com/robinhood-unofficial/pyrh/issues) of this repo and believe that this is not a duplicate.

# Description
pyrh fails to return a result when calling function `get_historical_quotes`

# Steps/Code to Reproduce
```python
stock = 'MSFT'
history = robinhood.get_historical_quotes(stock, '5minute', 'week')
```

# Results

_Expected_: historical data
_Actual_: Error on the following line (https://github.com/robinhood-unofficial/pyrh/blob/master/pyrh/robinhood.py#L197) that reads
```
TypeError: unsupported operand type(s) for +: 'URL' and 'str'
```
<img width="668" alt="Screen Shot 2020-04-23 at 11 10 14 PM" src="https://user-images.githubusercontent.com/4401818/80174497-66006500-85b8-11ea-94a2-65e56162e2bc.png">

# Versions
```python
>>> import platform; print(platform.platform())
Darwin-19.2.0-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.7.6 (default, Dec 30 2019, 19:38:26) 
[Clang 11.0.0 (clang-1100.0.33.16)]
>>> import pyrh; print("pyrh", pyrh.__version__)
pyrh 2.0
```

**Comment by adithyabsk** [comment]
@samueleishion That likely is a bug, we're in the middle of major re-factor and contributions are welcome.

**Comment by samueleishion** [comment]
_Suggested change_: Replace these lines https://github.com/robinhood-unofficial/pyrh/blob/master/pyrh/robinhood.py#L188-L198 with the following: 
```python
historicals = (urls.HISTORICALS.with_query([
        ('symbols', ",".join(stock).upper()),
        ('interval', interval),
        ('span', span),
        ('bounds', bounds.name.lower())
]))
```

**Comment by samueleishion** [comment]
@adithyabsk just saw your reply... are you taking PRs?

**Comment by adithyabsk** [comment]
@samueleishion yep

**Comment by samueleishion** [comment]
@adithyabsk branch off and into master?

**Comment by adithyabsk** [comment]
Yep, just fork the project and commit to master and create a PR (so you're not blocked)

**Comment by samueleishion** [comment]
Hey @adithyabsk I've created a PR but it seems to fail when running on Python 3.7.6 with a relatively vague error... any thoughts? 
https://github.com/robinhood-unofficial/pyrh/pull/230

**Comment by adithyabsk** [comment]
@samueleishion I commented on the PR

**Comment by stevenvo** [comment]
I encountered similar error but on _securities_owned()_

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-36-eeb4f4878ff3> in <module>
----> 1 rh.securities_owned()

~/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pyrh/robinhood.py in securities_owned(self)
    652         """
    653 
--> 654         return self.get(urls.POSITIONS + "?nonzero=true")
    655 
    656     ###########################################################################

TypeError: unsupported operand type(s) for +: 'URL' and 'str'
```

Version
```
import platform; print(platform.platform())
macOS-10.15.5-x86_64-i386-64bit

import sys; print("Python", sys.version)
Python 3.8.3 (default, Jul 14 2020, 00:27:13) 
[Clang 11.0.0 (clang-1100.0.33.8)]

print("pyrh", pyrh.__version__)
pyrh 2.0
```
