### ISSUE TITLE
pip install pyrh doesn't seem to pull the latest version

### ISSUE THREAD

**Issue by emptyopen** [robinhood-unofficial/pyrh#234]
I'm looking to use stuff like load_session / dump_session which I can see is in cache.py. However, the pip command doesn't seem to download everything in the latest version?

I've tried pip uninstalling and pip installing again, same issue. 

![image](https://user-images.githubusercontent.com/18575100/80288788-29835500-86ef-11ea-8730-ea228a10c01a.png)

**Comment by hnguyen2k** [comment]
I am seeing the same problem. I just started using this library today. Is there a forum where we can ask questions about this repo? Thanks!

**Comment by emptyopen** [comment]
I ended up just downloading a zip and replacing the contents in site_packages manually, which ended up working. Would be nice to be able to use pip somehow, I see options might potentially be added as a branch and it would be nice to just upgrade then.

**Comment by adithyabsk** [comment]
Please see: https://github.com/robinhood-unofficial/pyrh/issues/221#issuecomment-610541174

**Comment by adithyabsk** [comment]
@hnguyen2k Feel free to ask any questions by opening up an issue.
