### ISSUE TITLE
Please add the documentation page to the front page of the repo?

### ISSUE THREAD

**Issue by Emnolope** [robinhood-unofficial/pyrh#237]
There is no link to the main docs in the repo's md document. This is a simple addition I think would fare well. (No it is not obvious, I've stumbled around for 30 minutes before finding that url.)

**Comment by adithyabsk** [comment]
Good idea, I'll add it when I get a chance

**Comment by thiteixeira** [comment]
Wasn't this added already? I'd change to a `h3` tag though

<img width="509" alt="Screen Shot 2020-07-10 at 11 47 43 AM" src="https://user-images.githubusercontent.com/7052789/87173069-3271d480-c2a3-11ea-8c2b-39f6a5c49a45.png">


https://github.com/robinhood-unofficial/pyrh/blob/master/README.rst#please-note-that-parts-of-this-project-maybe-non-functional--under-rapid-development
