### ISSUE TITLE
rh.place_market_buy_order 400 Client Error: Bad Request for url: https://api.robinhood.com/orders/

### ISSUE THREAD

**Issue by Emnolope** [robinhood-unofficial/pyrh#238]
```
rh=Robinhood(username="yabbadabbadoo@stone.flint",password="dinodung")
rh.place_market_buy_order(instrument_URL='https://robinhood.com/stocks/F', symbol='F', quantity=1,time_in_force="GFD")
```
returns
```400 Client Error: Bad Request for url: https://api.robinhood.com/orders/```

**Comment by adithyabsk** [comment]
@Emnolope If that is your password, I would change it ASAP

**Comment by adithyabsk** [comment]
I'll take a look, it's likely many parts of the app aren't fully functional, yet. PRs are welcome.

**Comment by Emnolope** [comment]
Ahh I got it working with this tidbit:
```
STOCK1=pyrh.urls.instruments('STOCK')
import requests
requests.get(STOCK1)
STOCK2=requests.get(STOCK1).json()['results'][0]['url']
rh.place_market_buy_order(instrument_URL=STOCK2, symbol='STOCK', quantity=1,time_in_force="GFD")
```

**Comment by adithyabsk** [comment]
Yeah, feel free to leave the issue open since this is a verified bug. Again, happy to take contributors here. I'm not too free for the next few weeks but will likely be working in force again later this month.
