### ISSUE TITLE
session caching

### ISSUE THREAD

**Issue by jgansl** [robinhood-unofficial/pyrh#241]
There is commenting for saving/loading session but could not find the implementation. Is there an alternative way to save/load the session. I found some some documentation that varied but still did not work.

**Comment by lucascassiano** [comment]
same problem here - anyone got it working? adding a `mfa code` all sessions isn't optimal for many applications.

**Comment by HenryFBP** [comment]
@jgansl  I implemented session caching thusly:

https://github.com/HenryFBP/robinhoodtest/blob/4fec545890c32430f92214216fffeabbba588428/main.py#L26
