### ISSUE TITLE
get_quote_list fails to split parameter 'stock' when multiple tickers are given

### ISSUE THREAD

**Issue by Calrider** [robinhood-unofficial/pyrh#243]
#### Checklist
- [ x] I am on the [latest](https://github.com/robinhood-unofficial/pyrh/releases/latest) pyrh version.
- [ x] I have searched the [issues](https://github.com/robinhood-unofficial/pyrh/issues) of this repo and believe that this is not a duplicate.

# Description

Robinhood.get_quote_list fails when given a single stock ticker or multiple stock tickers

# Steps/Code to Reproduce
```python
from pyrh import Robinhood

rh = Robinhood()
rh.login(username='xxxx', password='xxxx')

rh.get_quote_list(stock='MSFT') # raises KeyError: ''
rh.get_quote_list(stock='MSFT,XOM') #  raises RH_exception.InvalidTickerSymbol()
```
-->

# Results
list of stock data

# Versions

**Comment by ziegenbalg** [comment]
Hello @Calrider, I'm running into this bug too. Is there a reason you closed this ticket? Did you find a solution?
Thank you!
