### ISSUE TITLE
Robinhood.place_stop_loss_sell_order() fails with HTTP 400 Client Error 

### ISSUE THREAD

**Issue by Calrider** [robinhood-unofficial/pyrh#245]
#### Checklist
- [x ] I am on the [latest](https://github.com/robinhood-unofficial/pyrh/releases/latest) pyrh version.
- [ x] I have searched the [issues](https://github.com/robinhood-unofficial/pyrh/issues) of this repo and believe that this is not a duplicate.

# Description
Robinhood.place_stop_loss_sell_order() consistently raises the following error:
400 Client Error: Bad Request for url: https://api.robinhood.com/orders/

# Steps/Code to Reproduce

```python
from pyrh import Robinhood, load_session

rh = load_session()
quote = rh.get_quote('RBCN')
instrument_url = quote['instrument']
rh.place_stop_loss_sell_order(
    instrument_URL=instrument_url,
    symbol='RBCN',
    time_in_force='GTC',
    stop_price=7.90,
    quantity=1
)
```

# Results

Order should have been sent

# Versions

**Comment by tyunist** [comment]
Found the same issue. The root cause is:
`
'{"non_field_errors":["Stop market sell order requested, but price provided."]}'
`
Some mentioned [here](https://www.reddit.com/r/RobinHood/comments/e8aiwj/market_sell_order_requested_but_price_provided/) that 

> Edit: Looks like someone flipped a switch on the back end. Market orders used to require a price (set in the app to last execution) to set the collar. Now, the API is choking on that.

**Comment by cmaccarone** [comment]
did anyone find a solution to this? I am getting http 400 as well.
