### ISSUE TITLE
Get Current Portfolio

### ISSUE THREAD

**Issue by Arunprakash1990** [robinhood-unofficial/pyrh#267]
I get the below error message when I try to get the current Portfolio:

AttributeError: 'Robinhood' object has no attribute 'portfolio'

It would be great if you can help with this request, Thanks!

**Comment by thiteixeira** [comment]
I don't think `Robinhood.portofolio` is a valid method. See 
https://github.com/robinhood-unofficial/pyrh/blob/master/pyrh/robinhood.py

**Comment by ricardoprins** [comment]
Yeah. you should use portfolios() to get the portfolio.

It returns a JSON with the following structure:
{
    "url": _portfolio URL_,
    "account": _account URL_,
    "start_date": _account start date_,
    "market_value": _account market value_,
    "equity": _equity value_,
    "extetended_hours_market_value": _self explanatory_,
    "extended_hours_equity": _self explanatory_,
    "extended_hours_portfolio_equity": _self explanatory_,
    "last_core_market_value": _self explanatory_,
    "last_core_equity": _self explanatory_,
    "last_core_portfolio_equtity": _self explanatory_,
    "excess_margin": _self explanatory_,
    "excess_maintenance": _self explanatory_,
    "excess_margin_with_uncleared_deposits": _self explanatory_,
    "excess_maintenance_with_uncleared_deposits": _self explanatory_,
    "equity_prevucious_close": _self explanatory_,
    "portfolio_equity_previous_close": _self explanatory_,
    "adjusted_equity_previous_close": _self explanatory_,
    "adjusted_portfolio_equity_previous_close": _self explanatory_,
    "withdrawable_amount": _self explanatory_,
    "unwithdrawable_deposits": _self explanatory_,
    "unwithdrawable_grants": _self explanatory_
}

It is important to note that it is an aggregate value; 

If you want to get the individual value for your instruments, then the method is positions().
