### ISSUE TITLE
2FA error, no longer able to log in to any robinhood account

### ISSUE THREAD

**Issue by ghost** [robinhood-unofficial/pyrh#270]
#### Checklist
- [x ] I am on the [latest](https://github.com/robinhood-unofficial/pyrh/releases/latest) pyrh version.
- [x ] I have searched the [issues](https://github.com/robinhood-unofficial/pyrh/issues) of this repo and believe that this is not a duplicate.

# Description

**Comment by MasenProjects** [comment]
seems that making a new 2FA fixes this issue, however I am no longer receiving emails from robinhood if qr code is not directly supplied, could be an issue on their end.

**Comment by xConde** [comment]
I had to change my email on robinhood to a different email address to actually receive the email codes.

**Comment by imprint-extract** [comment]
Think I'm running into this as well. Am I supposed to get prompted for my 2FA code?
As soon as I run the script with rh.login(username, password) I get: 
"No 2FA Given
email code:"
But since 2FA is enabled, there is no email code. Am I missing an input param?
