### ISSUE TITLE
Robinhood API usage restriction

### ISSUE THREAD

**Issue by diogobotelho** [robinhood-unofficial/pyrh#275]
Hello everyone, sorry if this falls a little bit off topic, but I have been trading with robinhood api (intraday, so pretty frequent orders) and I received an email from Robinhood saying they detected frequent trades and that API trading is against their terms and conditions. I checked the Robinhood T&Cs and I coudnt find anything against API usage and traging, also nothing about frequent intraday trades. 
Has anyone received something similar?
Thank you

**Comment by vnguye34** [comment]
I haven't personally but I noticed with my experiments with crypto HFT, robinhood could not handle the flood of orders I sent.

**Comment by vnguye34** [comment]
@diogobotelho When I was running my script, it would send a crypto buy/call order but by the time it got sent, it wouldn't be filled and then my script would return an error when trying to do another call when it hasn't sold the previous order. 

During my runtime of 30 minutes, it created about 500 buy and call orders

I used a combination of this repo as well as as this fork I found in Issue #73 
https://github.com/josephjaspers/Robinhood

I think my implementation is just inefficent and currently has no way to verify if an order has been filled before moving in the script
