### ISSUE TITLE
'email code' blocker

### ISSUE THREAD

**Issue by JudeSafo** [robinhood-unofficial/pyrh#277]
I'm hitting:
"No 2FA Given
email code:"
prompt when i reach the rh.login(username=USERNAME, password=PASSWORD) step

Have not been able to proceed past this step. 

which prevents me from

#### Checklist
- [ ] I am on the [latest](https://github.com/robinhood-unofficial/pyrh/releases/latest) pyrh version.
- [ ] I have searched the [issues](https://github.com/robinhood-unofficial/pyrh/issues) of this repo and believe that this is not a duplicate.

# Description

# Steps/Code to Reproduce

# Results

# Versions

**Comment by Benboykin08** [comment]
I'm not sure if you are still running into this issue but I found a way around this by using pyotp and also enabling 2FA in robinhood app and using the google authenticator option it should look something like this:

import pyotp
import robinhood_stocks as r

totp = pyotp.TOTP("codefromRH").now()
print("Current OTP:", totp)

totp = pyotp.TOTP("codefromRH").now()
login = r.login(username='username', password='password', mfa_code=totp)
