### ISSUE TITLE
AuthenticationError: Email code is no longer supported. Please request SMS code sent to your phone number.

### ISSUE THREAD

**Issue by diogobotelho** [robinhood-unofficial/pyrh#279]
Anyone having this recent message when logging in? Does this mean robinhood is not supporting email codes anymore?

**Comment by HaxOh** [comment]
Getting the same issue, haven't had much time to work on it. The SMS codes aren't working either though.

**Comment by zyxelenator** [comment]
Yeap, stopped working several days ago. No code arrives in email like before. If you switch to SMS, it does not work with that code...

**Comment by diogobotelho** [comment]
I can make it work with sms code.

________________________________

**Comment by zyxelenator** [comment]
> I can make it work with sms code.
> […](#)
> ________________________________ From: zyxelenator <notifications@github.com> Sent: Wednesday, October 14, 2020 9:56:58 AM To: robinhood-unofficial/pyrh <pyrh@noreply.github.com> Cc: Diogo Botelho <diogo.botelho@live.com>; Author <author@noreply.github.com> Subject: Re: [robinhood-unofficial/pyrh] AuthenticationError: Email code is no longer supported. Please request SMS code sent to your phone number. (#279) Yeap, stopped working several days ago. No code arrives in email like before. If you switch to SMS, it does not work with that code... — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frobinhood-unofficial%2Fpyrh%2Fissues%2F279%23issuecomment-708420760&data=04%7C01%7C%7C2ade8e388dae4eed600408d8704904f8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637382806194425607%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vslnin6o1kkrDcojvIQRfHztygc6wk2N4Kn5%2FrxOFm0%3D&reserved=0>, or unsubscribe<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAESTZNXFROLQN3COTCANXX3SKWU2VANCNFSM4SNN7S3A&data=04%7C01%7C%7C2ade8e388dae4eed600408d8704904f8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637382806194435607%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=eMalgFcAVgg1YVhtep4%2B2lzjoO%2BAs%2BV%2BHf8M8sLq8d8%3D&reserved=0>.

After entering SMS code:

Traceback (most recent call last):
  File "/home/zyxelenator/.local/lib/python3.6/site-packages/pyrh/robinhood.py", line 215, in login
    res2.raise_for_status()
  File "/home/zyxelenator/.local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.robinhood.com/challenge//respond/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "RobinhoodBot.py", line 11, in <module>
    rh.login(username="blablab", password="blabla")
  File "/home/zyxelenator/.local/lib/python3.6/site-packages/pyrh/robinhood.py", line 228, in login
    raise RH_exception.LoginFailed()
pyrh.exceptions.LoginFailed

**Comment by HaxOh** [comment]
> I can make it work with sms code.

Care to share what you've done to get it working with the sms code?

**Comment by diogobotelho** [comment]
I just use this:

from pyrh import Robinhood
rh=robinhood(username=rhlg, password=rhpa, challenge_type=rhlg_challengetype)
rh.login()

rhlg_challengetype=”sms”

let me know if you get any error with this.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by HaxOh** [comment]
Works great! Thanks!

**Comment by tannerarriza** [comment]
I am still getting the same error @zyxelenator was getting with the code you recommended @diogobotelho , I am currently running pyrh version 2.0 and when I introspect on the constructor function, it tells me that it has no parameters

`import inspect
inspect.signature(Robinhood.__init__)

>>> <Signature (self)>`

**Comment by diogobotelho** [comment]
> I am still getting the same error @zyxelenator was getting with the code you recommended @diogobotelho , I am currently running pyrh version 2.0 and when I introspect on the constructor function, it tells me that it has no parameters. I am also using Python 3.8.
> 
> import inspect
> inspect.signature(Robinhood.**init**)
> 
> returns --> <Signature (self)>
> 
> Are the rest of you who got it working using a different version? Any help is greatly appreciated.

"https://api.robinhood.com/challenge//respond/" is incorrect (two "/"). 
I had q similar problem before with the .cancel_order() function and I had to change the code to make it work so it requests from the correct url.
Not sure what is the best way to fix this. Can someone help?

**Comment by hyperstripe50** [comment]
I encountered this error when I had 2FA set to SMS for my Robinhood account. To fix the issue I did the following

1.  Disable 2FA by logging in online. See [here](https://robinhood.com/us/en/support/articles/twofactor-authentication)
2. Set `challenge_type` to `sms`
```python 
from pyrh import Robinhood
rh = Robinhood()
rh.login(username=xxxx, password=xxxx, challenge_type="sms")
rh.get_quote('AAPL')
```
Even though 2FA was disabled, I still received an SMS message with a code. 
```
> No 2FA Given
sms code:
xxxxx
```
```json
{
  "ask_price": "116.820000",
  "ask_size": 25,
  "bid_price": "116.000000",
  "bid_size": 4,
  "last_trade_price": "116.590000",
  "last_extended_hours_trade_price": "116.460000",
  "previous_close": "116.030000",
  "adjusted_previous_close": "116.030000",
  "previous_close_date": "2020-11-25",
  "symbol": "AAPL",
  "trading_halted": false,
  "has_traded": true,
  "last_trade_price_source": "consolidated",
  "updated_at": "2020-11-27T22:00:00Z",
  "instrument": "https://api.robinhood.com/instruments/450dfc6d-5510-4d40-abfb-f633b7d9be3e/"
}
```

**Comment by zyxelenator** [comment]
> I encountered this error when I had 2FA set to SMS for my Robinhood account. To fix the issue I did the following
> 
> 1. Disable 2FA by logging in online. See [here](https://robinhood.com/us/en/support/articles/twofactor-authentication)
> 2. Set `challenge_type` to `sms`
> 
> ```python
> from pyrh import Robinhood
> rh = Robinhood()
> rh.login(username=xxxx, password=xxxx, challenge_type="sms")
> rh.get_quote('AAPL')
> ```
> 
> Even though 2FA was disabled, I still received an SMS message with a code.
> 
> ```
> > No 2FA Given
> sms code:
> xxxxx
> ```
> 
> ```json
> {
>   "ask_price": "116.820000",
>   "ask_size": 25,
>   "bid_price": "116.000000",
>   "bid_size": 4,
>   "last_trade_price": "116.590000",
>   "last_extended_hours_trade_price": "116.460000",
>   "previous_close": "116.030000",
>   "adjusted_previous_close": "116.030000",
>   "previous_close_date": "2020-11-25",
>   "symbol": "AAPL",
>   "trading_halted": false,
>   "has_traded": true,
>   "last_trade_price_source": "consolidated",
>   "updated_at": "2020-11-27T22:00:00Z",
>   "instrument": "https://api.robinhood.com/instruments/450dfc6d-5510-4d40-abfb-f633b7d9be3e/"
> }
> ```

Thanks. I had the same, the only part I was missing is disabling 2FA in my robinhood account! Now it works with SMS code.
