### ISSUE TITLE
place_stop_loss_sell_order conflict with submit_sell_order sanity check

### ISSUE THREAD

**Issue by doudoujay** [robinhood-unofficial/pyrh#286]
#### Checklist
- [ x] I am on the [latest](https://github.com/robinhood-unofficial/pyrh/releases/latest) pyrh version.
- [ x] I have searched the [issues](https://github.com/robinhood-unofficial/pyrh/issues) of this repo and believe that this is not a duplicate.

# Description
place_stop_loss_sell_order is conflicting with submit_sell_order

# Steps/Code to Reproduce
inside submit_sell_order
```
       if trigger == "stop":
            if stop_price is None:
                raise (
                    ValueError(
                        "Stop order has no stop_price in call to submit_sell_order"
                    )
                )
            if price <= 0:
                raise (
                    ValueError(
                        "Stop_price must be positive number in call to "
                        "submit_sell_order"
                    )
                )
```
Do you mean if stop_price <= 0?

**Comment by sunil3590** [comment]
@doudoujay i think you are right. I faced the same issue. What did you end up doing?
