### ISSUE TITLE
Invalid Ticker symbol error on every single request

### ISSUE THREAD

**Issue by TannerTek** [robinhood-unofficial/pyrh#294]
When running the following code 

from pyrh import Robinhood

rh = Robinhood()
rh.login(username="****", password="******", qr_code="***********")

rh.bid_price(stock="AAPL")

I get the following error 

Exception has occurred: InvalidTickerSymbol
401 Client Error: Unauthorized for url: https://api.robinhood.com/quotes/AAPL/

I have no idea why and was wondering if someone has a solution

**Comment by adithyabsk** [comment]
Yeah--I can repro

Looks like some legacy code is no longer working--if someone wants to submit a PR. Happy to merge

**Comment by RobertAgee** [comment]
I believe this issue has been resolved.  All symbols I've tried are working for me.
